// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtb_warp_integration__Syms.h"


void Vtb_warp_integration___024root__trace_chg_0_sub_0(Vtb_warp_integration___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtb_warp_integration___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_warp_integration___024root__trace_chg_0\n"); );
    // Init
    Vtb_warp_integration___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb_warp_integration___024root*>(voidSelf);
    Vtb_warp_integration__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtb_warp_integration___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtb_warp_integration___024root__trace_chg_0_sub_0(Vtb_warp_integration___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb_warp_integration__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_warp_integration___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[1U] 
                     | vlSelf->__Vm_traceActivity[2U]))) {
        bufp->chgBit(oldp+0,(vlSelf->tb_warp_integration__DOT__rst_n));
        bufp->chgBit(oldp+1,(vlSelf->tb_warp_integration__DOT__cmd_valid));
        bufp->chgCData(oldp+2,(vlSelf->tb_warp_integration__DOT__cmd_funct),7);
        bufp->chgCData(oldp+3,(vlSelf->tb_warp_integration__DOT__cmd_rd),5);
        bufp->chgIData(oldp+4,(vlSelf->tb_warp_integration__DOT__cmd_rs1_data),32);
        bufp->chgIData(oldp+5,(vlSelf->tb_warp_integration__DOT__cmd_rs2_data),32);
        bufp->chgBit(oldp+6,(vlSelf->tb_warp_integration__DOT__resp_ready));
        bufp->chgIData(oldp+7,(vlSelf->tb_warp_integration__DOT__test_count),32);
        bufp->chgIData(oldp+8,(vlSelf->tb_warp_integration__DOT__pass_count),32);
        bufp->chgIData(oldp+9,(vlSelf->tb_warp_integration__DOT__fail_count),32);
        bufp->chgIData(oldp+10,(vlSelf->tb_warp_integration__DOT__send_rocc_cmd__Vstatic__timeout),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[3U])) {
        bufp->chgBit(oldp+11,(vlSelf->tb_warp_integration__DOT__cmd_ready));
        bufp->chgBit(oldp+12,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__resp_valid_r));
        bufp->chgCData(oldp+13,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__resp_rd_r),5);
        bufp->chgIData(oldp+14,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__resp_data_r),32);
        bufp->chgBit(oldp+15,(vlSelf->tb_warp_integration__DOT__dut__DOT__kernel_start));
        bufp->chgIData(oldp+16,(vlSelf->tb_warp_integration__DOT__dut__DOT__kernel_addr),32);
        bufp->chgSData(oldp+17,(vlSelf->tb_warp_integration__DOT__dut__DOT__kernel_length),16);
        bufp->chgBit(oldp+18,(vlSelf->tb_warp_integration__DOT__dut__DOT__kernel_done));
        bufp->chgBit(oldp+19,(vlSelf->tb_warp_integration__DOT__dut__DOT__kernel_error));
        bufp->chgBit(oldp+20,(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_update));
        bufp->chgCData(oldp+21,(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_value),8);
        bufp->chgCData(oldp+22,(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r),8);
        bufp->chgBit(oldp+23,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_pop));
        bufp->chgIData(oldp+24,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem
                                [vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__read_ptr]),32);
        bufp->chgBit(oldp+25,((0U != (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__count))));
        bufp->chgBit(oldp+26,((0x10U == (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__count))));
        bufp->chgBit(oldp+27,((0U == (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__count))));
        bufp->chgBit(oldp+28,(vlSelf->tb_warp_integration__DOT__dut__DOT__lane_execute));
        bufp->chgIData(oldp+29,(vlSelf->tb_warp_integration__DOT__dut__DOT__lane_instruction),32);
        bufp->chgBit(oldp+30,(vlSelf->tb_warp_integration__DOT__dut__DOT__lane_ready));
        bufp->chgCData(oldp+31,(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__state_r),3);
        bufp->chgCData(oldp+32,((((0U == (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__state_r)) 
                                  << 5U) | (((2U == (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__state_r)) 
                                             << 4U) 
                                            | (((4U 
                                                 == (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__state_r)) 
                                                << 3U) 
                                               | (((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__kernel_error) 
                                                   << 2U) 
                                                  | (0U 
                                                     == (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__count))))))),6);
        bufp->chgCData(oldp+33,(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__state_next),3);
        bufp->chgSData(oldp+34,(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__inst_count),16);
        bufp->chgBit(oldp+35,(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__kernel_start_r));
        bufp->chgIData(oldp+36,(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__kernel_addr_r),32);
        bufp->chgSData(oldp+37,(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__kernel_length_r),16);
        bufp->chgIData(oldp+38,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[0]),32);
        bufp->chgIData(oldp+39,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[1]),32);
        bufp->chgIData(oldp+40,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[2]),32);
        bufp->chgIData(oldp+41,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[3]),32);
        bufp->chgIData(oldp+42,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[4]),32);
        bufp->chgIData(oldp+43,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[5]),32);
        bufp->chgIData(oldp+44,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[6]),32);
        bufp->chgIData(oldp+45,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[7]),32);
        bufp->chgIData(oldp+46,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[8]),32);
        bufp->chgIData(oldp+47,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[9]),32);
        bufp->chgIData(oldp+48,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[10]),32);
        bufp->chgIData(oldp+49,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[11]),32);
        bufp->chgIData(oldp+50,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[12]),32);
        bufp->chgIData(oldp+51,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[13]),32);
        bufp->chgIData(oldp+52,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[14]),32);
        bufp->chgIData(oldp+53,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__fifo_mem[15]),32);
        bufp->chgCData(oldp+54,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__write_ptr),4);
        bufp->chgCData(oldp+55,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__read_ptr),4);
        bufp->chgCData(oldp+56,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_inst__DOT__count),5);
        bufp->chgCData(oldp+57,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__lane_ready),8);
        bufp->chgBit(oldp+58,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__0__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+59,((1U & (IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r))));
        bufp->chgCData(oldp+60,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+61,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+62,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+63,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+64,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+65,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+66,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+67,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+68,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+69,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+70,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+71,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+72,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+73,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+74,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+76,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+78,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+80,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+82,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+83,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+84,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+85,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+86,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+87,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+88,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+89,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+90,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+91,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+92,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+93,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+94,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+95,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+96,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+97,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+98,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+99,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+100,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+101,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+102,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+103,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+104,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+105,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+106,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+107,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+108,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+109,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+110,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+111,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+112,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+113,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+114,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+115,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+116,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__0__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+117,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__1__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+118,((1U & ((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r) 
                                      >> 1U))));
        bufp->chgCData(oldp+119,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+120,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+121,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+122,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+123,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+124,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+125,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+126,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+127,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+128,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+129,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+130,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+131,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+132,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+133,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+135,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+137,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+139,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+141,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+142,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+143,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+144,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+145,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+146,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+147,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+148,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+149,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+150,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+151,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+152,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+153,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+154,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+155,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+156,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+157,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+158,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+159,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+160,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+161,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+162,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+163,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+164,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+165,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+166,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+167,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+168,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+169,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+170,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+171,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+172,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+173,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+174,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+175,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__1__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+176,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__2__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+177,((1U & ((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r) 
                                      >> 2U))));
        bufp->chgCData(oldp+178,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+179,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+180,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+181,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+182,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+183,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+184,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+185,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+186,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+187,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+188,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+189,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+190,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+191,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+192,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+194,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+196,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+198,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+200,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+201,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+202,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+203,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+204,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+205,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+206,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+207,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+208,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+209,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+210,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+211,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+212,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+213,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+214,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+215,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+216,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+217,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+218,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+219,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+220,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+221,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+222,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+223,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+224,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+225,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+226,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+227,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+228,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+229,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+230,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+231,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+232,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+233,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+234,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__2__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+235,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__3__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+236,((1U & ((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r) 
                                      >> 3U))));
        bufp->chgCData(oldp+237,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+238,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+239,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+240,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+241,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+242,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+243,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+244,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+245,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+246,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+247,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+248,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+249,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+250,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+251,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+253,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+255,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+257,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+259,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+260,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+261,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+262,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+263,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+264,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+265,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+266,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+267,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+268,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+269,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+270,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+271,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+272,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+273,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+274,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+275,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+276,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+277,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+278,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+279,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+280,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+281,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+282,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+283,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+284,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+285,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+286,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+287,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+288,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+289,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+290,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+291,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+292,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+293,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__3__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+294,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__4__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+295,((1U & ((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r) 
                                      >> 4U))));
        bufp->chgCData(oldp+296,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+297,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+298,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+299,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+300,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+301,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+302,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+303,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+304,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+305,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+306,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+307,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+308,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+309,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+310,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+312,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+314,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+316,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+318,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+319,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+320,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+321,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+322,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+323,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+324,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+325,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+326,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+327,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+328,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+329,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+330,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+331,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+332,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+333,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+334,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+335,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+336,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+337,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+338,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+339,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+340,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+341,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+342,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+343,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+344,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+345,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+346,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+347,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+348,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+349,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+350,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+351,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+352,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__4__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+353,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__5__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+354,((1U & ((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r) 
                                      >> 5U))));
        bufp->chgCData(oldp+355,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+356,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+357,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+358,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+359,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+360,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+361,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+362,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+363,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+364,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+365,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+366,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+367,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+368,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+369,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+371,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+373,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+375,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+377,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+378,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+379,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+380,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+381,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+382,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+383,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+384,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+385,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+386,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+387,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+388,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+389,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+390,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+391,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+392,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+393,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+394,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+395,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+396,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+397,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+398,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+399,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+400,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+401,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+402,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+403,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+404,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+405,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+406,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+407,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+408,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+409,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+410,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+411,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__5__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+412,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__6__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+413,((1U & ((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r) 
                                      >> 6U))));
        bufp->chgCData(oldp+414,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+415,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+416,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+417,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+418,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+419,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+420,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+421,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+422,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+423,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+424,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+425,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+426,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+427,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+428,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+430,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+432,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+434,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+436,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+437,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+438,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+439,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+440,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+441,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+442,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+443,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+444,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+445,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+446,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+447,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+448,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+449,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+450,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+451,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+452,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+453,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+454,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+455,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+456,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+457,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+458,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+459,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+460,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+461,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+462,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+463,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+464,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+465,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+466,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+467,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+468,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+469,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+470,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__6__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgBit(oldp+471,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT____Vcellout__gen_lanes__BRA__7__KET____DOT__lane_inst__ready));
        bufp->chgBit(oldp+472,((1U & ((IData)(vlSelf->tb_warp_integration__DOT__dut__DOT__mask_inst__DOT__mask_r) 
                                      >> 7U))));
        bufp->chgCData(oldp+473,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__opcode),4);
        bufp->chgCData(oldp+474,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__dst_addr),5);
        bufp->chgCData(oldp+475,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__src1_addr),5);
        bufp->chgCData(oldp+476,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__src2_addr),5);
        bufp->chgIData(oldp+477,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__imm),32);
        bufp->chgIData(oldp+478,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_read_data1),32);
        bufp->chgIData(oldp+479,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_read_data2),32);
        bufp->chgBit(oldp+480,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_write_en));
        bufp->chgIData(oldp+481,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_write_data),32);
        bufp->chgIData(oldp+482,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_result),32);
        bufp->chgBit(oldp+483,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_overflow));
        bufp->chgCData(oldp+484,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__state_r),2);
        bufp->chgCData(oldp+485,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__state_next),2);
        bufp->chgIData(oldp+486,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__inst_r),32);
        bufp->chgQData(oldp+487,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_result_ext),33);
        bufp->chgQData(oldp+489,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_result_ext),64);
        bufp->chgQData(oldp+491,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_mul_result),64);
        bufp->chgQData(oldp+493,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_inst__DOT__fma_result_ext),33);
        bufp->chgBit(oldp+495,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_inst__DOT__mul_ovf));
        bufp->chgBit(oldp+496,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__alu_inst__DOT__add_ovf));
        bufp->chgIData(oldp+497,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[0]),32);
        bufp->chgIData(oldp+498,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[1]),32);
        bufp->chgIData(oldp+499,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[2]),32);
        bufp->chgIData(oldp+500,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[3]),32);
        bufp->chgIData(oldp+501,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[4]),32);
        bufp->chgIData(oldp+502,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[5]),32);
        bufp->chgIData(oldp+503,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[6]),32);
        bufp->chgIData(oldp+504,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[7]),32);
        bufp->chgIData(oldp+505,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[8]),32);
        bufp->chgIData(oldp+506,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[9]),32);
        bufp->chgIData(oldp+507,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[10]),32);
        bufp->chgIData(oldp+508,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[11]),32);
        bufp->chgIData(oldp+509,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[12]),32);
        bufp->chgIData(oldp+510,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[13]),32);
        bufp->chgIData(oldp+511,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[14]),32);
        bufp->chgIData(oldp+512,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[15]),32);
        bufp->chgIData(oldp+513,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[16]),32);
        bufp->chgIData(oldp+514,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[17]),32);
        bufp->chgIData(oldp+515,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[18]),32);
        bufp->chgIData(oldp+516,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[19]),32);
        bufp->chgIData(oldp+517,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[20]),32);
        bufp->chgIData(oldp+518,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[21]),32);
        bufp->chgIData(oldp+519,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[22]),32);
        bufp->chgIData(oldp+520,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[23]),32);
        bufp->chgIData(oldp+521,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[24]),32);
        bufp->chgIData(oldp+522,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[25]),32);
        bufp->chgIData(oldp+523,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[26]),32);
        bufp->chgIData(oldp+524,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[27]),32);
        bufp->chgIData(oldp+525,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[28]),32);
        bufp->chgIData(oldp+526,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[29]),32);
        bufp->chgIData(oldp+527,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[30]),32);
        bufp->chgIData(oldp+528,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__registers[31]),32);
        bufp->chgIData(oldp+529,(vlSelf->tb_warp_integration__DOT__dut__DOT__lanes_inst__DOT__gen_lanes__BRA__7__KET____DOT__lane_inst__DOT__rf_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgCData(oldp+530,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__opcode_r),7);
        bufp->chgIData(oldp+531,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__cmd_rs1_data_r),32);
        bufp->chgIData(oldp+532,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__cmd_rs2_data_r),32);
        bufp->chgCData(oldp+533,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__cmd_state_r),2);
    }
    bufp->chgBit(oldp+534,(vlSelf->tb_warp_integration__DOT__clk));
    bufp->chgBit(oldp+535,(vlSelf->tb_warp_integration__DOT__dut__DOT__ctrl_mem_req));
    bufp->chgIData(oldp+536,(vlSelf->tb_warp_integration__DOT__dut__DOT__controller_inst__DOT__fetch_addr),32);
    bufp->chgBit(oldp+537,(vlSelf->tb_warp_integration__DOT__mem_resp_valid));
    bufp->chgBit(oldp+538,(vlSelf->tb_warp_integration__DOT__mem_resp_ready));
    bufp->chgIData(oldp+539,(vlSelf->tb_warp_integration__DOT__mem_resp_data),32);
    bufp->chgIData(oldp+540,(vlSelf->tb_warp_integration__DOT__monitor_counter),32);
    bufp->chgIData(oldp+541,(vlSelf->tb_warp_integration__DOT__mem_req_count),32);
    bufp->chgBit(oldp+542,(vlSelf->tb_warp_integration__DOT__dut__DOT__fifo_push));
    bufp->chgCData(oldp+543,(vlSelf->tb_warp_integration__DOT__dut__DOT__rocc_inst__DOT__cmd_state_next),2);
}

void Vtb_warp_integration___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_warp_integration___024root__trace_cleanup\n"); );
    // Init
    Vtb_warp_integration___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb_warp_integration___024root*>(voidSelf);
    Vtb_warp_integration__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
}
